services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:11.13.4
    labels:
      - dev.orbstack.domains=asus-press-cms.local
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      RATE_LIMITER_ENABLED: true
      EXTENSIONS_AUTO_RELOAD: true
      PM2_AUTO_RESTART: true
      HSTS_ENABLED: true

      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 15000
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${FRONTEND_URL}
      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "'self'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__STYLE_SRC: "'self' 'unsafe-inline'"

      CORS_ENABLED: true
      CORS_ORIGIN: ${DIRECTUS_PUBLIC_URL}
      ALLOWED_ORIGINS: ${DIRECTUS_PUBLIC_URL}

      QUERY_LIMIT_MAX: 200
      GRAPHQL_INTROSPECTION: true

      SESSION_COOKIE_SECURE: true
      SESSION_COOKIE_SAME_SITE: 'Strict'
      
      # Docker compose specific environment variables...

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_AUTO_PURGE: 'true'
      REDIS: 'redis://cache:6379'

      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_ROOT: './uploads'

