services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:11.13.4
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      PUBLIC_URL: 'http://localhost:8055'
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_AUTO_PURGE: 'true'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'dev@tenten.co'
      ADMIN_PASSWORD: 'd1r3ctu5'

      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_ROOT: './uploads'

      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 15000

      HSTS_ENABLED: true

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "asus-press-staging.tenten.dev"
      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "'self'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__STYLE_SRC: "'self' 'unsafe-inline'"

      CORS_ENABLED: true
      CORS_ORIGIN: 'http://localhost:8055'
      ALLOWED_ORIGINS: 'http://localhost:8055'

      RATE_LIMITER_ENABLED: true

      QUERY_LIMIT_MAX: 200
      GRAPHQL_INTROSPECTION: true
      
      EXTENSIONS_AUTO_RELOAD: true
      PM2_AUTO_RESTART: true

      SESSION_COOKIE_SECURE: true
      SESSION_COOKIE_SAME_SITE: 'Strict'